apiVersion: v1
kind: ReplicationController
metadata:
  name: carl-2
spec:
  replicas: 1
  selector:
    app: carl-2
    group: carl
  template:
    metadata:
      name: carl-2
      labels:
        app: carl-2
        group: carl
    spec:
      containers:
      - name: carl-2
        image: gcr.io/aosman-alpha/carl:v1.0.2
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 80

