apiVersion: v1
kind: ReplicationController
metadata:
  name: carl-1
spec:
  replicas: 1
  selector:
    app: carl-1
    group: carl
  template:
    metadata:
      name: carl-1
      labels:
        app: carl-1
        group: carl
    spec:
      containers:
      - name: carl-1
        image: aosman/carl:v1.0.2
        command: [ "/bin/sh", "-c", "env" ]
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 80

