Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.provision "file", source: "../rel/carl/releases/0.0.1/carl.tar.gz", destination: "/home/vagrant/code/carl.tar.gz"
  config.vm.provision :shell, path: "bootstrap-vagrant.sh"
end
